#!/usr/bin/python3
from os import getenv
from sys import stdout
from py_compile import compile
pyfile = getenv("PYFILE", "")
stdout.write(" ".join(("Compiling", pyfile, "...\n")))
compile(pyfile, cfile="{}c".format(pyfile))
